### ISSUE TITLE
Incorrect distance value or distance unit

### ISSUE THREAD

**Issue by mkyral** [FreemapSlovakia/toposcope-maker#10]
Tested on Lysá Hora (Beskydy). Result shows a distance to Smrk 6 953,7 km, but correct is 6,9 km (or 6 953,7m)

![toposcope_distancies](https://cloud.githubusercontent.com/assets/155542/23042323/8165a53a-f498-11e6-827e-93f07ce2f2d3.png)

**Comment by zdila** [comment]
What an obvious bug. Caused by a08887b405d235b08c9d727b121b97f8045ee8b2. Thanks for reporting!
