### ISSUE TITLE
Too big font in preview

### ISSUE THREAD

**Issue by mkyral** [FreemapSlovakia/toposcope-maker#12]
The font in the preview is too big. At least on  Firefox 45 (ESR) on Gentoo Linux. Generated SVG is correct.

![toposcope_font_size](https://cloud.githubusercontent.com/assets/155542/23059245/db337ad2-f4f8-11e6-9a46-197d1067841f.png)

**Comment by kaylesk** [comment]
Turn off (set to "none") "minimum font size:" in Settings -> Content -> Advanced.

**Comment by mkyral** [comment]
Thanks. It looks better now. But it is strange as I had 12 there and texts were much bigger. Maybe some wrong calculation to resolution (I have FullHD now)?

**Comment by zdila** [comment]
For me it looks OK in FF 47 (ESR) and FF 51 without changing minimum font size. Also OK in Chrome 56 and Inkscape.

**Comment by mkyral** [comment]
Strange. Both texts "OpenStreetMap contributors"  and "Smrk ..." have the same font size: 11px.
But looks different.

![toposcope_font_size2](https://cloud.githubusercontent.com/assets/155542/23061864/c09c1aca-f503-11e6-9d6d-10524ce725e9.png)

**Comment by zdila** [comment]
I'll try FF 45 in the evening, but it is and older browser... There is already FF 47 ESR :-)

**Comment by mkyral** [comment]
47 or 45.7? I have 45.7 and can't find 47. Even on Mozilla website:  https://www.mozilla.org/en-US/firefox/organizations/faq/

```
[I] www-client/firefox
     Available versions:  45.6.0-r1^d 45.7.0^d ~51.0^d 
```

Will try FF 51.

**Comment by zdila** [comment]
Oh, you are right, it is 45.7.0. So in 45.7.0 it is OK on my machine (Debian Stretch).

**Comment by mkyral** [comment]
Well, I tested with a fresh profile and it is displayed correct. So probably some plugin or obsolete setting :-(

**Comment by zdila** [comment]
Great. So I am closing this issue.
