### ISSUE TITLE
Anchoring

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/toposcope-maker#14]
I'm not sure if I understand it. I have problem with editing SVG in Inscape. Letters of the compas and text betwen this letters are anchored to some strange point far outside of the circle. If will be possible, it would be good anchoring it to the center of the circle.
Thanks :)

**Comment by zdila** [comment]
Note that text are just placed on the line, no anchors are set anywhere. I'll try to check it.

**Comment by zdila** [comment]
It is problem of Inkscape. I've tried to manually create a line and put some random text on it. This text had then anchor placed also at some "random" place.

**Comment by zdila** [comment]
Note that I've simplified the generated SVG so that you can modify the straight lines in Inkscape.

**Comment by seg-on** [comment]
OK. I found solution to me. To Group objects together. Make changes and after ungroup objects.
The note is for this issue? I don't understant it.

**Comment by zdila** [comment]
Yes :-). Just ignore if not related at all.
