### ISSUE TITLE
Hungarian translation ready

### ISSUE THREAD

**Issue by debyos** [FreemapSlovakia/toposcope-maker#19]
Dear All,
I have created a [Hungarian translation](https://github.com/FreemapSlovakia/toposcope-maker/files/3573649/toposcope-hu.zip) to the toposcope-maker. If you think it is nice, please [put in online](https://github.com/FreemapSlovakia/toposcope-maker/tree/3a9990b434f7a390ffa072d327081b9bd4258b22/i18n). Thanks in advance!

**Comment by zdila** [comment]
Integrated and deployed. Thanks!
