### ISSUE TITLE
Doesn't see to work on a global scale

### ISSUE THREAD

**Issue by The-Artist-1** [FreemapSlovakia/toposcope-maker#23]
I'm trying to create a toposcope on a global scale and the orientation seems to be way off.  Eg Nauru is SE of "Birmingham" but the toposcope has it north. Unsure what's going on here but hope you can help sort it
![Toposcope test incorrect](https://user-images.githubusercontent.com/101558108/158151368-760be1a3-a748-4424-9323-6f6f557b0091.jpg)

**Comment by zdila** [comment]
It is actually correct, please see line from Birmingham to Nauru at https://earth.google.com/earth/d/1Pd3dywNLRXgTcj1lQlGVkiLjrDGui7B_?usp=sharing
